In [4]:
import numpy as np

In [5]:
#1.有多少學生英文成績比數學成績高?
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])

In [6]:
np.greater(english_score, math_score)

array([False,  True,  True, False, False,  True])

In [7]:
#2.是否全班同學最高分都是國文?
chinese_score = np.array([65,90,82,72,66,77])

In [9]:
a=np.greater(chinese_score, english_score)
a

array([ True,  True,  True,  True,  True,  True])

In [10]:
b=np.greater(chinese_score, math_score)
b

array([ True,  True,  True,  True,  True,  True])

In [11]:
np.equal(a, b)

array([ True,  True,  True,  True,  True,  True])

In [12]:
np.logical_and(a, b).all()

True